[versions]
agp = "8.2.1"
kotlin = "1.9.0"
ktLint = "11.6.0"
detekt = "1.19.0"

core-ktx = "1.12.0"
org-jetbrains-kotlin-jvm = "1.9.0"
appcompat = "1.6.1"
material = "1.11.0"
lifecycle = "2.7.0"
activity-compose = "1.8.2"
compose-bom = "2023.08.00"
coroutines = "1.7.3"
ktor = "2.3.7"
koinCore = "3.5.3"
koinCompose = "1.1.2"
koinAndroid = "3.5.3"
koinAndroidxCompose = "3.5.3"
kotlinxSerializationJson = "1.6.2"
kotlinxDateTime = "0.5.0"
sqlDelight = "2.0.1"
leakCanary = "2.12"
napier = "2.6.1"
navigation = "2.7.6"
coil = "1.4.0"
playServicesLocation = "21.0.1"
playServicesMaps = "18.2.0"
multiplatformSettings = "1.1.1"
buildKonfig = "0.13.3"
composeMultiplatform = "1.5.11"
splashscreen = "1.1.0-alpha02"
konveyor = "1.0.3"
mockk = "1.13.9"

truth = "1.1.3"
junit = "4.13.2"
androidArchCoreTesting = "1.1.1"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
mockative = "2.0.1"
androidXJUnit = "1.1.5"
robolectric = "4.11.1"
firebase-analytics = "21.5.0"

[plugins]
ktLint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktLint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlinX-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
nativeCocoapod = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
compose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
livedata-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinCompose" }
kotlinX-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
sqlDelight = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }
sqlDelight-coroutine = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
kotlinX-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
multiplatformSettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }
splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

# Test libs
junit = { module = "junit:junit", version.ref = "junit" }
androidX-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidXJUnit" }
kotlinX-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
mockative = { module = "io.mockative:mockative", version.ref = "mockative" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
android-test-core = { module = "android.arch.core:core-testing", version.ref = "androidArchCoreTesting" }
androidX-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
konveyor = { module = "com.github.vacxe:konveyor", version.ref = "konveyor" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
google-truth = { module = "com.google.truth:truth", version.ref = "truth" }
roboelectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebase-analytics" }

